name: daily-discord-challenge

on:
  schedule:
    # Adjust UTC time to your desired local time
    - cron: "0 21 * * *"   # 07:00 AEST
  workflow_dispatch: {}    # Manual trigger option

permissions:
  contents: write  # commit state.json

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run bot
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node bot.js

      - name: Commit state
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update state [skip ci]"
            git push
          fi
