name: daily-discord-challenge

on:
  schedule:
    # Cron: 07:00 AEST (UTC+10) → 21:00 UTC
    - cron: "0 21 * * *"
  workflow_dispatch: {}  # allows manual run

permissions:
  contents: write  # so we can commit state.json

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run bot
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node bot.js

      - name: Commit state
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "Update state.json [skip ci]"
            git push
          fi

